# non-harmful development profile settings
# these can be included in the production jar

logging:
  level:
    org:
      springframework:
        security: ERROR
      hibernate:
        SQL:
          INFO
        type:
          descriptor:
            sql:
              BasicBinder:
                INFO
web:
  security:
    debug: false
